---
- name: install coturn
  apt:
    pkg: coturn
    state: present

- name: ensure coturn is enabled and running
  block:
    - name: ensure coturn is enabled
      lineinfile:
        dest: /etc/default/coturn
        line: TURNSERVER_ENABLED=1
        regexp: "^#?TURNSERVER_ENABLED="

    - name: enable coturn service
      ansible.builtin.service:
        name: coturn
        state: started
        enabled: true

- name: Create parameters for Diffie–Hellman (could take a while)
  command: "openssl dhparam -out /etc/ssl/coturn-dh-{{ turn_dhparam_length }}.pem {{ turn_dhparam_length }}"
  args:
    creates: /etc/ssl/coturn-dh-{{ turn_dhparam_length }}.pem
  notify: restart coturn

- name: deploy config
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart coturn